### ISSUE TITLE
report errors

### ISSUE THREAD

**Issue by SKININ** [kruvcraft21/GGIl2cpp#7]
Hello, sir, I used this on the Android 10 mobile phone, and reported an error in the modifier. The following is what I reported an error.

 luaj.LuaError: error loading module 'Il2cppApi':
/storage/emulated/0/备份与创作/动态/tt.lua:1
`require("Il2cppApi")`
load Il2cppApi.lua: luaj.LuaError: /storage/emulated/0/备份与创作/动态/Il2cppApi.lua:1824
`    FindGlobalMetaData = function(self)`
'}' expected (to close '{' at line 1820) near 'FindGlobalMetaData' (global 'require')
level = 1, const = 10, proto = 0, upval = 1, vars = 8, code = 25
CALL v0..v1
 ; PC 2 CODE 0100401D OP 29 A 0 B 2 C 1 Bx 1025 sBx -130046
stack traceback:
	/storage/emulated/0/备份与创作/动态/tt.lua:1 in main chunk
	[Java]: in ?
	at luaj.LuaValue.error(LuaValue.java:997)
	at luaj.Globals.loadfile(Globals.java:255)
	at luaj.lib.PackageLib$lua_searcher.invoke(PackageLib.java:299)
	at luaj.lib.PackageLib$require.call(PackageLib.java:231)
	at luaj.LuaClosure.execute(LuaClosure.java:534)
	at luaj.LuaClosure.call(LuaClosure.java:160)
	at android.ext.Script.runScript(Script.java:6018)
	at android.ext.Script$ScriptThread.run(Script.java:5747)
Caused by: luaj.LuaError: /storage/emulated/0/备份与创作/动态/Il2cppApi.lua:1824
`    FindGlobalMetaData = function(self)`
'}' expected (to close '{' at line 1820) near 'FindGlobalMetaData'
	at luaj.compiler.LexState.lexerror(LexState.java:295)
	at luaj.compiler.LexState.syntaxerror(LexState.java:299)
	at luaj.compiler.LexState.check_match(LexState.java:1021)
	at luaj.compiler.LexState.constructor(LexState.java:1381)
	at luaj.compiler.LexState.simpleexp(LexState.java:1619)
	at luaj.compiler.LexState.subexpr(LexState.java:1741)
	at luaj.compiler.LexState.expr(LexState.java:1759)
	at luaj.compiler.LexState.explist(LexState.java:1459)
	at luaj.compiler.LexState.localstat(LexState.java:2132)
	at luaj.compiler.LexState.statement(LexState.java:2254)
	at luaj.compiler.LexState.statlist(LexState.java:2290)
	at luaj.compiler.LexState.body(LexState.java:1449)
	at luaj.compiler.LexState.simpleexp(LexState.java:1624)
	at luaj.compiler.LexState.subexpr(LexState.java:1741)
	at luaj.compiler.LexState.expr(LexState.java:1759)
	at luaj.compiler.LexState.explist(LexState.java:1462)
	at luaj.compiler.LexState.funcargs(LexState.java:1479)
	at luaj.compiler.LexState.suffixedexp(LexState.java:1574)
	at luaj.compiler.LexState.exprstat(LexState.java:2173)
	at luaj.compiler.LexState.statement(LexState.java:2273)
	at luaj.compiler.LexState.statlist(LexState.java:2290)
	at luaj.compiler.LexState.mainfunc(LexState.java:2306)
	at luaj.compiler.LuaC$CompileState.luaY_parser(LuaC.java:121)
	at luaj.compiler.LuaC.compile(LuaC.java:99)
	at luaj.Globals.compilePrototype(Globals.java:364)
	at luaj.Globals.loadPrototype(Globals.java:352)
	at luaj.Globals.load(Globals.java:267)
	at luaj.Globals.loadfile(Globals.java:249)
	... 6 more

**Comment by kruvcraft21** [comment]
@SKININ, Provide more information. Are you using a local copy of the script or loading it ?

**Comment by SKININ** [comment]
I used "require ('I2cppApi ') Il2cpp()" to call the file, and the error occurred after execution

**Comment by kruvcraft21** [comment]
@SKININ, check for compliance with the original file

**Comment by SKININ** [comment]
@kruvcraft21 The original file I used was downloaded from your GitHub. It works normally on the NOx simulator, but an error is reported when I use it on the mobile phone

**Comment by kruvcraft21** [comment]
@SKININ, It doesn't depend on the device. Check again for compliance with the module, as the lines specified in the error do not correspond to reality.

**Comment by kruvcraft21** [comment]
Or you can send it here, I'll check it out

**Comment by SKININ** [comment]
I only use "require ('I2cppApi ')) Il2cpp()" to try game Arkington, and an error occurs

**Comment by kruvcraft21** [comment]
@SKININ, It doesn't depend on the game or device. The problem is in the module itself, check its correctness or send it here.

**Comment by SKININ** [comment]
I found that the problem was that the game did not call dat, which led to an error @kruvcraft21

**Comment by kruvcraft21** [comment]
@SKININ, no, the error you showed is related to the incorrect reading of the script.

**Comment by kruvcraft21** [comment]
the dat file with the game has nothing to do with it

**Comment by kruvcraft21** [comment]
well, either you specified one error first, then another one arose
